INSERT INTO greetings (language, greeting) VALUES('SeSotho', 'Dumela');
INSERT INTO greetings (language, greeting) VALUES('French', 'Bonjour');
INSERT INTO greetings (language, greeting) VALUES('Sepedi', 'Thobela');
INSERT INTO greetings (language, greeting) VALUES('Spanish', 'Hola');
INSERT INTO greetings (language, greeting) VALUES('SeTswana', 'Dumela');
INSERT INTO greetings (language, greeting) VALUES('Japanese', 'Konnichiwa');
INSERT INTO greetings (language, greeting) VALUES('Xhosa', 'Molo');
INSERT INTO greetings (language, greeting) VALUES('Hebrew', 'Shalom');
INSERT INTO greetings (language, greeting) VALUES('Mandarin', 'Ni hao');
INSERT INTO greetings (language, greeting) VALUES('Swahili', 'Habari');
INSERT INTO greetings (language, greeting) VALUES('Yoruba', 'Bawo ni');
INSERT INTO greetings (language, greeting) VALUES('Bengali', 'Nomoshkar');
INSERT INTO greetings (language, greeting) VALUES('Fijian', 'Bula');
INSERT INTO greetings (language, greeting) VALUES('Afrikaans', 'Hallo');
